In [104]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plot
from sklearn.naive_bayes import GaussianNB
import math

In [106]:
inp = open('train.csv','r')
a = inp.readline()
f = a.split(',')
f = ["".join(i.split()) for i in f]
n = len(f)
train_X = pd.read_csv('train.csv',header=0,names=f)
train_Y = train_X['Survived']
del train_X['Survived']
del train_X['Name']
del train_X['Ticket']
del train_X['Cabin']
del train_X['Embarked']
train_X.head()
inp = open('test.csv','r')
f = f.remove('Survived')
test_X = pd.read_csv('test.csv',header=0,names=f)
del test_X['Name']
del test_X['Ticket']
del test_X['Cabin']
del test_X['Embarked']
# print(train_X)
print(test_X)

     PassengerId  Pclass     Sex   Age  SibSp  Parch      Fare
0            892       3    male  34.5      0      0    7.8292
1            893       3  female  47.0      1      0    7.0000
2            894       2    male  62.0      0      0    9.6875
3            895       3    male  27.0      0      0    8.6625
4            896       3  female  22.0      1      1   12.2875
5            897       3    male  14.0      0      0    9.2250
6            898       3  female  30.0      0      0    7.6292
7            899       2    male  26.0      1      1   29.0000
8            900       3  female  18.0      0      0    7.2292
9            901       3    male  21.0      2      0   24.1500
10           902       3    male   NaN      0      0    7.8958
11           903       1    male  46.0      0      0   26.0000
12           904       1  female  23.0      1      0   82.2667
13           905       2    male  63.0      1      0   26.0000
14           906       1  female  47.0      1      0   61.1750
15           907       2  female  24.0      1      0   27.7208
16           908       2    male  35.0      0      0   12.3500
17           909       3    male  21.0      0      0    7.2250
18           910       3  female  27.0      1      0    7.9250
19           911       3  female  45.0      0      0    7.2250
20           912       1    male  55.0      1      0   59.4000
21           913       3    male   9.0      0      1    3.1708
22           914       1  female   NaN      0      0   31.6833
23           915       1    male  21.0      0      1   61.3792
24           916       1  female  48.0      1      3  262.3750
25           917       3    male  50.0      1      0   14.5000
26           918       1  female  22.0      0      1   61.9792
27           919       3    male  22.5      0      0    7.2250
28           920       1    male  41.0      0      0   30.5000
29           921       3    male   NaN      2      0   21.6792
..           ...     ...     ...   ...    ...    ...       ...
388         1280       3    male  21.0      0      0    7.7500
389         1281       3    male   6.0      3      1   21.0750
390         1282       1    male  23.0      0      0   93.5000
391         1283       1  female  51.0      0      1   39.4000
392         1284       3    male  13.0      0      2   20.2500
393         1285       2    male  47.0      0      0   10.5000
394         1286       3    male  29.0      3      1   22.0250
395         1287       1  female  18.0      1      0   60.0000
396         1288       3    male  24.0      0      0    7.2500
397         1289       1  female  48.0      1      1   79.2000
398         1290       3    male  22.0      0      0    7.7750
399         1291       3    male  31.0      0      0    7.7333
400         1292       1  female  30.0      0      0  164.8667
401         1293       2    male  38.0      1      0   21.0000
402         1294       1  female  22.0      0      1   59.4000
403         1295       1    male  17.0      0      0   47.1000
404         1296       1    male  43.0      1      0   27.7208
405         1297       2    male  20.0      0      0   13.8625
406         1298       2    male  23.0      1      0   10.5000
407         1299       1    male  50.0      1      1  211.5000
408         1300       3  female   NaN      0      0    7.7208
409         1301       3  female   3.0      1      1   13.7750
410         1302       3  female   NaN      0      0    7.7500
411         1303       1  female  37.0      1      0   90.0000
412         1304       3  female  28.0      0      0    7.7750
413         1305       3    male   NaN      0      0    8.0500
414         1306       1  female  39.0      0      0  108.9000
415         1307       3    male  38.5      0      0    7.2500
416         1308       3    male   NaN      0      0    8.0500
417         1309       3    male   NaN      1      1   22.3583

[418 rows x 7 columns]

In [110]:
X = list(train_X.values)
Y = list(train_Y.values)
for i in X:
    if i[2] == "male":
        i[2] = 0
    else:
        i[2] = 1
    if math.isnan(i[3]):
        i[3] = 101.0
        
test = list(test_X.values)
for i in test:
    if i[2] == "male":
        i[2] = 0
    else:
        i[2] = 1
    if math.isnan(i[3]):
        i[3] = 101.0
    if math.isnan(i[6]):
        i[6] = 0.0
print(test[152])

[1044 3 0 60.5 0 0 0.0]

In [125]:
clf = GaussianNB()
clf.fit(X,Y)
t_Y = clf.predict(test)
out = open('gender_submission.csv','w')
count = 0
for i in t_Y:
    s = str(test[count][0])+","+str(i)
    print(test[count][0])
    count = count+1
    out.write(s)
    out.write("\n")
# print(t_Y)
# print(Y)

892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
1049
1050
1051
1052
1053
1054
1055
1056
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073
1074
1075
1076
1077
1078
1079
1080
1081
1082
1083
1084
1085
1086
1087
1088
1089
1090
1091
1092
1093
1094
1095
1096
1097
1098
1099
1100
1101
1102
1103
1104
1105
1106
1107
1108
1109
1110
1111
1112
1113
1114
1115
1116
1117
1118
1119
1120
1121
1122
1123
1124
1125
1126
1127
1128
1129
1130
1131
1132
1133
1134
1135
1136
1137
1138
1139
1140
1141
1142
1143
1144
1145
1146
1147
1148
1149
1150
1151
1152
1153
1154
1155
1156
1157
1158
1159
1160
1161
1162
1163
1164
1165
1166
1167
1168
1169
1170
1171
1172
1173
1174
1175
1176
1177
1178
1179
1180
1181
1182
1183
1184
1185
1186
1187
1188
1189
1190
1191
1192
1193
1194
1195
1196
1197
1198
1199
1200
1201
1202
1203
1204
1205
1206
1207
1208
1209
1210
1211
1212
1213
1214
1215
1216
1217
1218
1219
1220
1221
1222
1223
1224
1225
1226
1227
1228
1229
1230
1231
1232
1233
1234
1235
1236
1237
1238
1239
1240
1241
1242
1243
1244
1245
1246
1247
1248
1249
1250
1251
1252
1253
1254
1255
1256
1257
1258
1259
1260
1261
1262
1263
1264
1265
1266
1267
1268
1269
1270
1271
1272
1273
1274
1275
1276
1277
1278
1279
1280
1281
1282
1283
1284
1285
1286
1287
1288
1289
1290
1291
1292
1293
1294
1295
1296
1297
1298
1299
1300
1301
1302
1303
1304
1305
1306
1307
1308
1309

In [122]:
# inp = open('gender_submission.csv','r')
# print(inp.readline())
# print(inp.readline())

892,0

892,1